try {
  console.log(a);
  console.log(56);
}
catch (err) {
  console.log(err);
}

console.log(39);
